In [22]:
import warnings
import numpy as np
import pandas as pd
import plotly.express as px 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("raw_data.csv")
df.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [4]:
columns = df.columns
columns

Index(['Customer ID', 'Gender', 'Age', 'Married', 'Number of Dependents',
       'City', 'Zip Code', 'Latitude', 'Longitude', 'Number of Referrals',
       'Tenure in Months', 'Offer', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue', 'Customer Status', 'Churn Category', 'Churn Reason'],
      dtype='object')

## Drop unnecessary columns

In [9]:
new_df = df.copy()
cols2drop = ['Customer ID','Total Refunds','Zip Code','Latitude', 'Longitude','Churn Category', 'Churn Reason']
new_df.drop(cols2drop, axis=1,inplace=True)
print(f"Old Dataframe Shape: {df.shape}\nNew Dataframe shape: {new_df.shape}")

Old Dataframe Shape: (7043, 38)
New Dataframe shape: (7043, 31)

In [20]:
# chcecking number of unique values in each column
cols = new_df.columns
uniq = new_df.nunique()
for i in range(len(uniq)):
    print(f"Column Name: {cols[i]}\tData Type: {type(cols[i])}\tTotal Unique Value: {uniq[i]}")

Column Name: Gender	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Age	Data Type: <class 'str'>	Total Unique Value: 62
Column Name: Married	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Number of Dependents	Data Type: <class 'str'>	Total Unique Value: 10
Column Name: City	Data Type: <class 'str'>	Total Unique Value: 1106
Column Name: Number of Referrals	Data Type: <class 'str'>	Total Unique Value: 12
Column Name: Tenure in Months	Data Type: <class 'str'>	Total Unique Value: 72
Column Name: Offer	Data Type: <class 'str'>	Total Unique Value: 5
Column Name: Phone Service	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Avg Monthly Long Distance Charges	Data Type: <class 'str'>	Total Unique Value: 3583
Column Name: Multiple Lines	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Internet Service	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Internet Type	Data Type: <class 'str'>	Total Unique Value: 3
Column Name: Avg Monthly GB Download	Data Type: <class 'str'>	Total Unique Value: 49
Column Name: Online Security	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Online Backup	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Device Protection Plan	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Premium Tech Support	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Streaming TV	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Streaming Movies	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Streaming Music	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Unlimited Data	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Contract	Data Type: <class 'str'>	Total Unique Value: 3
Column Name: Paperless Billing	Data Type: <class 'str'>	Total Unique Value: 2
Column Name: Payment Method	Data Type: <class 'str'>	Total Unique Value: 3
Column Name: Monthly Charge	Data Type: <class 'str'>	Total Unique Value: 1591
Column Name: Total Charges	Data Type: <class 'str'>	Total Unique Value: 6540
Column Name: Total Extra Data Charges	Data Type: <class 'str'>	Total Unique Value: 16
Column Name: Total Long Distance Charges	Data Type: <class 'str'>	Total Unique Value: 6068
Column Name: Total Revenue	Data Type: <class 'str'>	Total Unique Value: 6975
Column Name: Customer Status	Data Type: <class 'str'>	Total Unique Value: 3

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_20244\2940761528.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"Column Name: {cols[i]}\tData Type: {type(cols[i])}\tTotal Unique Value: {uniq[i]}")

## Serarching for missing values

In [21]:
new_df.isna().sum()

Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                     1526
Streaming Music                      1526
Unlimited Data                       1526
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Customer Status                         0
dtype: int64

In [24]:
# % of missing values
(new_df.isnull().sum() / new_df.shape[0])*100

Gender                                0.000000
Age                                   0.000000
Married                               0.000000
Number of Dependents                  0.000000
City                                  0.000000
Number of Referrals                   0.000000
Tenure in Months                      0.000000
Offer                                55.047565
Phone Service                         0.000000
Avg Monthly Long Distance Charges     9.683374
Multiple Lines                        9.683374
Internet Service                      0.000000
Internet Type                        21.666903
Avg Monthly GB Download              21.666903
Online Security                      21.666903
Online Backup                        21.666903
Device Protection Plan               21.666903
Premium Tech Support                 21.666903
Streaming TV                         21.666903
Streaming Movies                     21.666903
Streaming Music                      21.666903
Unlimited Data                       21.666903
Contract                              0.000000
Paperless Billing                     0.000000
Payment Method                        0.000000
Monthly Charge                        0.000000
Total Charges                         0.000000
Total Extra Data Charges              0.000000
Total Long Distance Charges           0.000000
Total Revenue                         0.000000
Customer Status                       0.000000
dtype: float64

In [27]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame)
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

In [31]:
new_df=new_df.interpolate(method="linear")

C:\Users\VICTUS\AppData\Local\Temp\ipykernel_20244\1341497181.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df=new_df.interpolate(method="linear")

In [33]:
new_df=new_df.dropna()
new_df.isna().sum()

Gender                               0
Age                                  0
Married                              0
Number of Dependents                 0
City                                 0
Number of Referrals                  0
Tenure in Months                     0
Offer                                0
Phone Service                        0
Avg Monthly Long Distance Charges    0
Multiple Lines                       0
Internet Service                     0
Internet Type                        0
Avg Monthly GB Download              0
Online Security                      0
Online Backup                        0
Device Protection Plan               0
Premium Tech Support                 0
Streaming TV                         0
Streaming Movies                     0
Streaming Music                      0
Unlimited Data                       0
Contract                             0
Paperless Billing                    0
Payment Method                       0
Monthly Charge                       0
Total Charges                        0
Total Extra Data Charges             0
Total Long Distance Charges          0
Total Revenue                        0
Customer Status                      0
dtype: int64

In [36]:
def unique_values_names(df):
    for column in df:
        if df[column].dtype=='object':
            print(f'{column}:{df[column].unique()}')

In [37]:
unique_values_names(new_df)

Gender:['Male' 'Female']
Married:['No' 'Yes']
City:['Costa Mesa' 'Martinez' 'Midpines' 'Lompoc' 'Napa' 'Simi Valley'
 'La Mesa' 'Woodlake' 'San Marcos' 'Alpaugh' 'Moss Beach' 'Stockton'
 'Los Angeles' 'Yermo' 'Fremont' 'El Portal' 'Calistoga' 'North Hollywood'
 'Inverness' 'Modesto' 'Kenwood' 'Morongo Valley' 'Palo Verde' 'Valyermo'
 'Monterey Park' 'Big Oak Flat' 'Glenhaven' 'Lodi' 'Fairfield' 'Moorpark'
 'Solvang' 'Del Rey' 'Armona' 'Mckinleyville' 'Calimesa' 'Garden Grove'
 'Indio' 'San Diego' 'Escondido' 'Chino' 'Calexico' 'Groveland'
 'Los Gatos' 'Clovis' 'Buellton' 'Midway City' 'Folsom' 'San Clemente'
 'Bodega Bay' 'Challenge' 'Ludlow' 'Santa Clara' 'Rescue' 'Lotus'
 'Harbor City' 'Death Valley' 'Riverdale' 'Claremont' 'Upland'
 'Santa Rosa' 'Long Beach' 'Samoa' 'Milford' 'Anderson' 'Orange'
 'San Francisco' 'Santa Cruz' 'Lake Hughes' 'Paramount'
 'San Juan Capistrano' 'Copperopolis' 'Cypress' 'Lancaster' 'San Ysidro'
 'Gilroy' 'San Jose' 'Stanford' 'Turlock' 'Los Alamitos' 'Encinitas'
 'Sacramento' 'La Habra' 'Visalia' 'Whittier' 'Grass Valley' 'Herlong'
 'Mojave' 'Denair' 'Monterey' 'Palo Alto' 'Lomita' 'Kelseyville'
 'Pinecrest' 'Beale Afb' 'Greenville' 'Poway' 'Korbel' 'Pine Valley'
 'Bangor' 'Canyon Dam' 'Anza' 'Forest Ranch' 'Jamul' 'Petaluma' 'Hornitos'
 'Lafayette' 'Beverly Hills' 'Chester' 'Hilmar' 'Riverside' 'Etna'
 'Castro Valley' 'Comptche' 'Wasco' 'Irvine' 'Newhall' 'Murphys' 'Ceres'
 'Elk Grove' 'Wilton' 'Douglas City' 'White Water' 'Merced' 'Alviso'
 'Palm Springs' 'Rancho Cucamonga' 'Orleans' 'Elk' 'Bakersfield'
 'Placentia' 'Redwood City' 'Buena Park' 'Richmond' 'Yreka' 'Elverta'
 'Santa Barbara' 'Dutch Flat' 'Mi Wuk Village' 'Milpitas' 'West Hollywood'
 'Norco' 'Gold Run' 'Grover Beach' 'Covina' 'Adin' 'Mecca' 'Inglewood'
 'Temecula' 'June Lake' 'Brawley' 'Big Bear Lake' 'Grenada' 'Woodland'
 'Corona Del Mar' 'Newport Beach' 'Saratoga' 'Concord' 'Trinidad'
 'Columbia' 'Hamilton City' 'Pine Grove' 'Livermore' 'Lucerne Valley'
 'Honeydew' 'Coalinga' 'Cressey' 'Pittsburg' 'Sun City' 'Paradise'
 'Westlake Village' 'Felton' 'Klamath' 'Chico' 'Santa Ana' 'Winters'
 'Hesperia' 'Encino' 'Palmdale' 'Pleasant Grove' 'Thousand Palms'
 'Bodfish' 'Glendale' 'Fiddletown' 'Forbestown' 'Glen Ellen' 'Santee'
 'Acampo' 'Burbank' 'Sierra City' 'Cobb' 'El Dorado' 'Angelus Oaks'
 'Westwood' 'Shaver Lake' 'Fawnskin' 'Boonville' 'Pioneertown'
 'Klamath River' 'Grimes' 'Hood' 'Fresno' 'Byron' 'Winchester'
 'Oregon House' 'Fall River Mills' 'Shoshone' 'Garberville'
 'Desert Hot Springs' 'Torrance' 'Squaw Valley' 'Palermo'
 'Capistrano Beach' 'La Puente' 'Posey' 'Lakehead' 'Rodeo' 'San Joaquin'
 'Avila Beach' 'Santa Margarita' 'Montara' 'Planada' 'La Grange' 'Alamo'
 'Lee Vining' 'Huntington Park' 'Foothill Ranch' 'Ladera Ranch' 'Rio Dell'
 'Somis' 'National City' 'Old Station' 'Fellows' 'Emeryville'
 'Pearblossom' 'Palomar Mountain' 'Lake Forest' 'Woodbridge'
 'Canyon Country' 'Cottonwood' 'Mission Viejo' 'Firebaugh' 'San Lucas'
 'San Ramon' 'Santa Monica' 'San Bernardino' 'Downey' 'Madison'
 'Lemon Grove' 'Deer Park' 'Shasta' 'Walnut Creek' 'Gerber' 'Los Molinos'
 'Shafter' 'Guerneville' 'Cantua Creek' 'Bethel Island' 'Victorville'
 'Dos Palos' 'Calpine' 'Mentone' 'Freedom' 'Ojai' 'Citrus Heights'
 'Oakley' 'Rohnert Park' 'Fallbrook' 'Atherton' 'Wheatland' 'West Covina'
 'Cupertino' 'Tecate' 'Hickman' 'San Dimas' 'Pacoima' 'Wallace' 'Topanga'
 'Carlotta' 'Shingle Springs' 'Mira Loma' 'La Quinta' 'Salinas' 'Guinda'
 'Artesia' 'Penryn' 'Glenn' 'Westport' 'Imperial Beach' 'Lockwood'
 'Dana Point' 'Mountain View' 'Gridley' 'Pauma Valley' 'Hemet' 'Corcoran'
 'Dorris' 'Vacaville' 'Madera' 'Somerset' 'Perris' 'Upper Lake'
 'South El Monte' 'Orangevale' 'Pomona' 'Mad River' 'Redlands' 'Tujunga'
 'Cerritos' 'Coronado' 'Fish Camp' 'Placerville' 'Laytonville'
 'Forest Knolls' 'Templeton' 'Greenwood' 'Menlo Park' 'San Pedro' 'Igo'
 'Exeter' 'Woodland Hills' 'Malibu' 'Big Bend' 'Pasadena' 'Novato'
 'Compton' 'Sequoia National Park' 'Yuba City' 'Rio Vista' 'Millbrae'
 'Carson' 'Corona' 'Camino' 'Ranchita' 'San Mateo' 'Banning' 'Stevinson'
 'Davis' 'Anaheim' 'San Leandro' 'Chilcoot' 'Hume' 'Sunnyvale' 'Colusa'
 'Carmel' 'Sultana' 'Fountain Valley' 'Piru' 'Badger' 'Castella' 'Covelo'
 'Sun Valley' 'San Carlos' 'Ventura' 'Roseville' 'Clipper Mills' 'Piercy'
 'Chula Vista' 'Running Springs' 'Bonita' 'Sylmar' 'Meadow Vista'
 'Lakewood' 'Rancho Cordova' 'Manchester' 'Big Bear City' 'Gualala'
 'Dublin' 'California City' 'Santa Clarita' 'Mammoth Lakes' 'Vista'
 'Likely' 'Catheys Valley' 'Mc Farland' 'Sunset Beach' 'Murrieta' 'Benton'
 'Tehachapi' 'Santa Maria' 'Blythe' 'March Air Reserve Base' 'Graton'
 'Bayside' 'Meridian' 'Pope Valley' 'Mount Laguna' 'Termo' 'Tahoe Vista'
 'Chualar' 'Bloomington' 'Newport Coast' 'Oroville' 'Sheep Ranch' 'Traver'
 'Olancha' 'Ione' 'Raymond' 'Mccloud' 'Sloughhouse' 'El Cajon' 'Vallejo'
 'Menifee' 'La Jolla' 'Manteca' 'Rancho Santa Fe' 'Paso Robles'
 'Greenview' 'Oceanside' 'Redding' 'Los Banos' 'Bonsall' 'Jamestown'
 'Altadena' 'Hopland' 'Platina' 'Mc Kittrick' 'Sutter Creek' 'Van Nuys'
 'Willows' 'Morro Bay' 'Salyer' 'Guadalupe' 'Potrero' 'Fontana' 'Sonora'
 'Ramona' 'Scott Bar' 'Independence' 'Ballico' 'Cedar Glen' 'Granite Bay'
 'Doyle' 'Berkeley' 'South Pasadena' 'Barstow' 'Myers Flat' 'Dulzura'
 'Sierraville' 'Ontario' 'Fullerton' 'Angels Camp' 'Valencia' 'Tollhouse'
 'Five Points' 'Hathaway Pines' 'Kyburz' 'Grizzly Flats' 'Alpine'
 'Paicines' 'Pollock Pines' 'Venice' 'Valley Ford' 'Crockett'
 'South Dos Palos' 'Redwood Valley' 'Soledad' 'Hydesville' 'Clements'
 'Orange Cove' 'Jolon' 'Standish' 'Borrego Springs' 'Diamond Springs'
 'Dobbins' 'Playa Del Rey' 'Montrose' 'Campo Seco' 'Blue Lake'
 'Pebble Beach' 'Mill Creek' 'El Monte' 'Knights Landing' 'Glennville'
 'Hayward' 'Fowler' 'Travis Afb' 'Reseda' 'Monrovia' 'Lincoln' 'Aromas'
 'Thermal' 'King City' 'Whitmore' 'Ukiah' 'Oceano' 'Yorba Linda' 'Alturas'
 'Brea' 'Phillipsville' 'Carmel By The Sea' 'Sausalito' 'Coarsegold'
 'Homewood' 'La Verne' 'Belmont' 'Forks Of Salmon' 'Nuevo' 'Willits'
 'Keene' 'Ducor' 'Brownsville' 'Nipton' 'Junction City' 'Santa Paula'
 'Weed' 'Tustin' 'Rowland Heights' 'Smartville' 'Porter Ranch' 'Marina'
 'Castaic' 'Trabuco Canyon' 'Crows Landing' 'Tehama' 'Helendale'
 'Saint Helena' 'Paynes Creek' 'Bella Vista' 'Alhambra' 'Somes Bar'
 'San Gabriel' 'Camp Nelson' 'Downieville' 'Hanford' 'Escalon' 'Campo'
 'Long Barn' 'Janesville' 'Hermosa Beach' 'Aguanga' 'Shingletown'
 'Thousand Oaks' 'Bishop' 'Atwater' 'Yucaipa' 'Kneeland' 'Rancho Mirage'
 'Forest Falls' 'Goleta' 'Bell' 'Hawaiian Gardens' 'Glencoe' 'Rialto'
 'Daggett' 'La Palma' 'Pinon Hills' 'Davis Creek' 'Oakland' 'Bass Lake'
 'French Camp' 'Callahan' 'Olema' 'Biola' 'Raisin City' 'Litchfield'
 'San Quentin' 'Temple City' 'Tupman' 'Pacific Palisades' 'Yucca Valley'
 'Boulder Creek' 'Greenfield' 'Pismo Beach' 'Arroyo Grande'
 'Lake Elsinore' 'Port Costa' 'Lemon Cove' 'San Gregorio' 'Pico Rivera'
 'Wildomar' 'Springville' 'Manhattan Beach' 'Avalon' 'Glendora' 'Lindsay'
 'Manton' 'Maywood' 'Darwin' 'North San Juan' 'Daly City' 'Summerland'
 'Fair Oaks' 'Atascadero' 'Witter Springs' 'Walnut' 'Frazier Park'
 'Norwalk' 'Fortuna' 'Phelan' 'Port Hueneme' 'Fillmore' 'Petrolia'
 'Gasquet' 'Cloverdale' 'Gustine' 'California Hot Springs' 'Twain Harte'
 'Live Oak' 'Union City' 'Forestville' 'Bieber' 'Redondo Beach' 'Tuolumne'
 'Miranda' 'Delano' 'Butte City' 'Lockeford' 'Silverado' 'Farmersville'
 'O Neals' 'Penngrove' 'Miramonte' 'Occidental' 'La Canada Flintridge'
 'Mount Hermon' 'Westminster' 'Hornbrook' 'Dunnigan' 'Hercules'
 'Echo Lake' 'Friant' 'Half Moon Bay' 'West Sacramento' 'Huntington Beach'
 'Los Osos' 'Tahoe City' 'Pioneer' 'Grand Terrace' 'Mcarthur' 'Corning'
 'Spring Valley' 'Moreno Valley' 'Lynwood' 'San Jacinto' 'El Cerrito'
 'Caliente' 'Edwards' 'Winnetka' 'Lakeshore' 'Thornton' 'Niland' 'Woody'
 'Applegate' 'Weaverville' 'Le Grand' 'Calipatria' 'Montclair'
 'Santa Ynez' 'Gardena' 'Greenbrae' 'Carlsbad' 'Smith River' 'Surfside'
 'Burney' 'Canoga Park' 'Suisun City' 'El Segundo' 'Reedley'
 'Santa Ysabel' 'Alderpoint' 'Delhi' 'Ahwahnee' 'Rocklin' 'Twin Bridges'
 'Redcrest' 'Topaz' 'Winton' 'Goodyears Bar' 'Aliso Viejo' 'San Rafael'
 'Winterhaven' 'Dixon' 'Moraga' 'Canby' 'Cambria' 'Valley Village'
 'Stonyford' 'Seal Beach' 'Pescadero' 'Landers' 'Birds Landing' 'Antioch'
 'San Marino' 'Pilot Hill' 'Fort Bidwell' 'Danville' 'Marshall' 'Lakeside'
 'Sutter' 'Chino Hills' 'Desert Center' 'Big Bar' 'Sierra Madre'
 'Pleasant Hill' 'Oak View' 'Heber' 'Potter Valley' 'Hughson'
 'Valley Springs' 'Oakhurst' 'Essex' 'Esparto' 'Clio' 'Pacifica'
 'Madeline' 'Orosi' 'Beaumont' 'Twentynine Palms' 'Markleeville' 'Angwin'
 'Mariposa' 'Lebec' 'South San Francisco' 'Maxwell' 'Rosemead'
 'Oro Grande' 'Albion' 'Plymouth' 'Sherman Oaks' 'Cardiff By The Sea'
 'Navarro' 'Mountain Center' 'Cabazon' 'Indian Wells' 'Earlimart' 'Galt'
 'Loma Linda' 'Leggett' 'Fort Bragg' 'San Lorenzo' 'Joshua Tree'
 'Palo Cedro' 'Eagleville' 'Livingston' 'Fulton' 'Adelanto' 'Mt Baldy'
 'Pleasanton' 'Orinda' 'Kings Beach' 'Vina' 'Big Pine' 'West Point'
 'Creston' 'North Palm Springs' 'French Gulch' 'Three Rivers' 'Cayucos'
 'Wilseyville' 'Albany' 'San Fernando' 'Gonzales' 'El Dorado Hills'
 'Clarksburg' 'Portola Valley' 'Lathrop' 'Laguna Hills' 'Cool' 'Paskenta'
 'San Andreas' 'Mendocino' 'Montebello' 'Lytle Creek' 'Loleta'
 'South Gate' 'Baldwin Park' 'Coulterville' 'Northridge' 'Bodega'
 'Ocotillo' 'Shandon' 'Rancho Santa Margarita' 'Branscomb' 'Red Bluff'
 'Cathedral City' 'Weott' 'Olympic Valley' 'Willow Creek' 'Portola'
 'Laguna Niguel' 'Patterson' 'Granada Hills' 'Auberry' 'Lawndale' 'Caspar'
 'Hat Creek' 'San Simeon' 'Los Altos' 'Azusa' 'San Martin' 'Pala' 'Burson'
 'Diamond Bar' 'Fields Landing' 'Moss Landing' 'North Hills' 'Davenport'
 'Oxnard' 'Newcastle' 'Brentwood' 'Shasta Lake' 'Herald' 'San Bruno'
 'Selma' 'Sugarloaf' 'Point Reyes Station' 'Parker Dam' 'Lemoore'
 'Mill Valley' 'Bellflower' 'Mather' 'Keeler' 'Millville' 'Wrightwood'
 'Lucerne' 'Yorkville' 'Rancho Palos Verdes' 'Crestline' 'El Nido'
 'Kettleman City' 'Stirling City' 'El Sobrante' 'Mineral' 'Stanton'
 'Newark' 'Lake Isabella' 'Stinson Beach' 'Arnold' 'Bridgeport'
 'Marina Del Rey' 'Soulsbyville' 'Twain' 'Coachella' 'Annapolis' 'Duarte'
 'Morgan Hill' 'Pinole' 'Seeley' 'San Pablo' 'Nicasio' 'Philo' 'Rosamond'
 'Porterville' 'Nice' 'Lake Arrowhead' 'Huron' 'Littlerock' 'Healdsburg'
 'Garden Valley' 'Carpinteria' 'Redway' 'Wilmington' 'Camptonville'
 'Jacumba' 'North Highlands' 'Stratford' 'Vallecito' 'Wendel'
 'Walnut Grove' 'Palm Desert' 'Los Olivos' 'Los Alamos' 'Kirkwood'
 'Princeton' 'Avenal' 'La Honda' 'Volcano' 'San Ardo' 'Lewiston'
 'Dos Rios' 'Solana Beach' 'Monte Rio' 'Seaside' 'Lamont' 'Casmalia'
 'Penn Valley' 'West Hills' 'Carmichael' 'Salida' 'Valley Center'
 'South Lake Tahoe' 'Brooks' 'Burlingame' 'Studio City' 'La Mirada'
 'Kingsburg' 'Palos Verdes Peninsula' 'Llano' 'Riverbank']
Offer:['Offer E' 'Offer D' 'Offer A' 'Offer B' 'Offer C']
Phone Service:['Yes']
Multiple Lines:['No' 'Yes']
Internet Service:['Yes']
Internet Type:['Fiber Optic' 'Cable' 'DSL']
Online Security:['No' 'Yes']
Online Backup:['No' 'Yes']
Device Protection Plan:['Yes' 'No']
Premium Tech Support:['No' 'Yes']
Streaming TV:['No' 'Yes']
Streaming Movies:['No' 'Yes']
Streaming Music:['No' 'Yes']
Unlimited Data:['Yes' 'No']
Contract:['Month-to-Month' 'Two Year' 'One Year']
Paperless Billing:['Yes' 'No']
Payment Method:['Bank Withdrawal' 'Credit Card' 'Mailed Check']
Customer Status:['Churned' 'Stayed' 'Joined']

In [ ]:
pd.to